
# This file is automatically generated, you probably don't want to edit this

dtaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dtaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            indep = NULL,
            split = 75,
            method = "Class",
            Control = 15, ...) {

            super$initialize(
                package="DTAMAC",
                name="dta",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..indep <- jmvcore::OptionVariables$new(
                "indep",
                indep)
            private$..split <- jmvcore::OptionNumber$new(
                "split",
                split,
                min=0,
                max=100,
                default=75)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "Class",
                    "Anova"),
                default="Class")
            private$..Control <- jmvcore::OptionNumber$new(
                "Control",
                Control,
                min=1,
                max=100,
                default=15)

            self$.addOption(private$..dep)
            self$.addOption(private$..indep)
            self$.addOption(private$..split)
            self$.addOption(private$..method)
            self$.addOption(private$..Control)
        }),
    active = list(
        dep = function() private$..dep$value,
        indep = function() private$..indep$value,
        split = function() private$..split$value,
        method = function() private$..method$value,
        Control = function() private$..Control$value),
    private = list(
        ..dep = NA,
        ..indep = NA,
        ..split = NA,
        ..method = NA,
        ..Control = NA)
)

dtaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dtaResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Decision Tree Analysis")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Classification using Decision Tree"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot of Decision Tree",
                width=750,
                height=850,
                renderFun=".plot"))}))

dtaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dtaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DTAMAC",
                name = "dta",
                version = c(1,0,0),
                options = options,
                results = dtaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Decision Tree Analysis
#'
#' 
#' @param data .
#' @param dep .
#' @param indep .
#' @param split .
#' @param method .
#' @param Control .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
dta <- function(
    data,
    dep,
    indep,
    split = 75,
    method = "Class",
    Control = 15) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("dta requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(indep)) indep <- jmvcore::resolveQuo(jmvcore::enquo(indep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(indep), indep, NULL))


    options <- dtaOptions$new(
        dep = dep,
        indep = indep,
        split = split,
        method = method,
        Control = Control)

    analysis <- dtaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

